/*
  # Rebuild Munros Database from Authentic Text Data
  
  This migration completely rebuilds the Munros table with authentic data from allmunros.txt
  
  1. Drops existing corrupted table
  2. Creates new table with proper structure
  3. Inserts all 282 authentic Scottish Munros
  4. Sets up proper RLS and policies
  
  Expected result: Exactly 282 authentic Munros
*/

-- Drop existing corrupted table
DROP TABLE IF EXISTS munros CASCADE;

-- Create new Munros table with proper structure
CREATE TABLE munros (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  height_m integer NOT NULL,
  height_ft integer NOT NULL,
  prominence_m integer NOT NULL DEFAULT 0,
  classification text NOT NULL DEFAULT 'Munro',
  region text NOT NULL,
  area text NOT NULL DEFAULT '',
  grid_ref text NOT NULL DEFAULT '',
  latitude numeric(10,7) NOT NULL DEFAULT 0,
  longitude numeric(10,7) NOT NULL DEFAULT 0,
  first_ascent_year integer,
  description text NOT NULL DEFAULT '',
  difficulty_rating integer NOT NULL DEFAULT 3 CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  estimated_time_hours numeric(3,1) NOT NULL DEFAULT 6.0,
  popular_routes jsonb NOT NULL DEFAULT '[]'::jsonb,
  best_seasons jsonb NOT NULL DEFAULT '["Spring", "Summer", "Autumn"]'::jsonb,
  significant_info text DEFAULT '',
  image_filename text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE munros ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Public read access for munros"
  ON munros
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- Create indexes for performance
CREATE INDEX idx_munros_name ON munros (name);
CREATE INDEX idx_munros_height ON munros (height_m DESC);
CREATE INDEX idx_munros_region ON munros (region);
CREATE INDEX idx_munros_location ON munros (region, area);

-- Insert authentic Munros data
INSERT INTO munros (
  name, height_m, height_ft, region, area, grid_ref, 
  description, difficulty_rating, estimated_time_hours, image_filename
) VALUES
  ('A'' Bhuidheanach Bheag', 936, 3071, 'Cairngorms', '', '', 'A'' Bhuidheanach Bheag is a 936m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'a_bhuidheanach_bheag.jpg'),
  ('A'' Chailleach (Fannichs)', 997, 3271, 'Ullapool', '', '', 'A'' Chailleach (Fannichs) is a 997m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'a_chailleach.jpg'),
  ('A'' Chailleach (Monadhliath)', 930, 3051, 'Cairngorms', '', '', 'A'' Chailleach (Monadhliath) is a 930m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'a_chailleach.jpg'),
  ('A'' Chralaig', 1120, 3675, 'Kintail', '', '', 'A'' Chralaig is a 1120m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'a_chralaig.jpg'),
  ('A'' Ghlas-bheinn', 918, 3012, 'Kintail', '', '', 'A'' Ghlas-bheinn is a 918m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'a_ghlas_bheinn.jpg'),
  ('A'' Mhaighdean', 967, 3173, 'Ullapool', '', '', 'A'' Mhaighdean is a 967m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'a_mhaighdean.jpg'),
  ('A'' Mharconaich', 975, 3199, 'Cairngorms', '', '', 'A'' Mharconaich is a 975m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'a_mharconaich.jpg'),
  ('Am Basteir', 934, 3064, 'Isle of Skye', '', '', 'Am Basteir is a 934m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'am_basteir.jpg'),
  ('Am Bodach', 1032, 3386, 'Fort William', '', '', 'Am Bodach is a 1032m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'am_bodach.jpg'),
  ('Am Faochagach', 954, 3130, 'Ullapool', '', '', 'Am Faochagach is a 954m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'am_faochagach.jpg'),
  ('An Caisteal', 995, 3264, 'Loch Lomond', '', '', 'An Caisteal is a 995m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'an_caisteal.jpg'),
  ('An Coileachan', 923, 3028, 'Ullapool', '', '', 'An Coileachan is a 923m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'an_coileachan.jpg'),
  ('An Gearanach', 982, 3222, 'Fort William', '', '', 'An Gearanach is a 982m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'an_gearanach.jpg'),
  ('An Riabhachan', 1129, 3704, 'Loch Ness', '', '', 'An Riabhachan is a 1129m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'an_riabhachan.jpg'),
  ('An Sgarsoch', 1006, 3301, 'Cairngorms', '', '', 'An Sgarsoch is a 1006m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'an_sgarsoch.jpg'),
  ('An Socach (Affric)', 921, 3022, 'Loch Ness', '', '', 'An Socach (Affric) is a 921m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'an_socach.jpg'),
  ('An Socach (Braemar)', 944, 3097, 'Cairngorms', '', '', 'An Socach (Braemar) is a 944m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'an_socach.jpg'),
  ('An Socach (Mullardoch)', 1069, 3507, 'Loch Ness', '', '', 'An Socach (Mullardoch) is a 1069m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'an_socach.jpg'),
  ('An Stùc', 1118, 3668, 'Perthshire', '', '', 'An Stùc is a 1118m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'an_stuc.jpg'),
  ('Aonach Air Chrith', 1021, 3350, 'Kintail', '', '', 'Aonach Air Chrith is a 1021m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'aonach_air_chrith.jpg'),
  ('Aonach Beag (Alder)', 1116, 3661, 'Cairngorms', '', '', 'Aonach Beag (Alder) is a 1116m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'aonach_beag.jpg'),
  ('Aonach Beag (Nevis Range)', 1234, 4049, 'Fort William', '', '', 'Aonach Beag (Nevis Range) is a 1234m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'aonach_beag.jpg'),
  ('Aonach Meadhoin', 1001, 3284, 'Kintail', '', '', 'Aonach Meadhoin is a 1001m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'aonach_meadhoin.jpg'),
  ('Aonach Mòr', 1221, 4006, 'Fort William', '', '', 'Aonach Mòr is a 1221m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'aonach_mor.jpg'),
  ('Beinn a'' Bhùird', 1197, 3927, 'Cairngorms', '', '', 'Beinn a'' Bhùird is a 1197m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_a_bhuird.jpg'),
  ('Beinn a'' Chaorainn (Cairngorms)', 1082, 3550, 'Cairngorms', '', '', 'Beinn a'' Chaorainn (Cairngorms) is a 1082m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_a_chaorainn.jpg'),
  ('Beinn a'' Chaorainn (Glen Spean)', 1050, 3445, 'Fort William', '', '', 'Beinn a'' Chaorainn (Glen Spean) is a 1050m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_a_chaorainn.jpg'),
  ('Beinn a'' Chlachair', 1087, 3566, 'Fort William', '', '', 'Beinn a'' Chlachair is a 1087m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_a_chlachair.jpg'),
  ('Beinn a'' Chlèibh', 916, 3005, 'Argyll', '', '', 'Beinn a'' Chlèibh is a 916m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_a_chleibh.jpg'),
  ('Beinn a'' Chochuill', 980, 3215, 'Argyll', '', '', 'Beinn a'' Chochuill is a 980m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_a_chochuill.jpg'),
  ('Beinn a'' Chreachain', 1081, 3547, 'Argyll', '', '', 'Beinn a'' Chreachain is a 1081m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_a_chreachain.jpg'),
  ('Beinn a'' Chròin', 942, 3091, 'Loch Lomond', '', '', 'Beinn a'' Chròin is a 942m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_a_chroin.jpg'),
  ('Beinn Achaladair', 1038, 3406, 'Argyll', '', '', 'Beinn Achaladair is a 1038m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_achaladair.jpg'),
  ('Beinn an Dòthaidh', 1004, 3294, 'Argyll', '', '', 'Beinn an Dòthaidh is a 1004m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_an_dothaidh.jpg'),
  ('Beinn Bheoil', 1019, 3343, 'Cairngorms', '', '', 'Beinn Bheoil is a 1019m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_bheoil.jpg'),
  ('Beinn Bhreac', 931, 3054, 'Cairngorms', '', '', 'Beinn Bhreac is a 931m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_bhreac.jpg'),
  ('Beinn Bhrotain', 1157, 3796, 'Cairngorms', '', '', 'Beinn Bhrotain is a 1157m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_bhrotain.jpg'),
  ('Beinn Bhuidhe', 948, 3110, 'Argyll', '', '', 'Beinn Bhuidhe is a 948m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_bhuidhe.jpg'),
  ('Beinn Chabhair', 933, 3061, 'Loch Lomond', '', '', 'Beinn Chabhair is a 933m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_chabhair.jpg'),
  ('Beinn Dearg (Blair Atholl)', 1008, 3307, 'Perthshire', '', '', 'Beinn Dearg (Blair Atholl) is a 1008m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_dearg.jpg'),
  ('Beinn Dearg (Ullapool)', 1084, 3556, 'Ullapool', '', '', 'Beinn Dearg (Ullapool) is a 1084m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_dearg.jpg'),
  ('Beinn Dòrain', 1076, 3530, 'Argyll', '', '', 'Beinn Dòrain is a 1076m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_dorain.jpg'),
  ('Beinn Dubhchraig', 978, 3209, 'Argyll', '', '', 'Beinn Dubhchraig is a 978m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_dubhchraig.jpg'),
  ('Beinn Èibhinn', 1102, 3615, 'Cairngorms', '', '', 'Beinn Èibhinn is a 1102m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_eibhinn.jpg'),
  ('Beinn Eunaich', 989, 3245, 'Argyll', '', '', 'Beinn Eunaich is a 989m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_eunaich.jpg'),
  ('Beinn Fhada', 1032, 3386, 'Kintail', '', '', 'Beinn Fhada is a 1032m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_fhada.jpg'),
  ('Beinn Fhionnlaidh', 959, 3146, 'Argyll', '', '', 'Beinn Fhionnlaidh is a 959m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_fhionnlaidh.jpg'),
  ('Beinn Fhionnlaidh (Càrn Eige)', 1005, 3297, 'Loch Ness', '', '', 'Beinn Fhionnlaidh (Càrn Eige) is a 1005m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_fhionnlaidh.jpg'),
  ('Beinn Ghlas', 1103, 3619, 'Perthshire', '', '', 'Beinn Ghlas is a 1103m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_ghlas.jpg'),
  ('Beinn Heasgarnich', 1078, 3537, 'Perthshire', '', '', 'Beinn Heasgarnich is a 1078m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_heasgarnich.jpg'),
  ('Beinn Ìme', 1011, 3317, 'Loch Lomond', '', '', 'Beinn Ìme is a 1011m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_ime.jpg'),
  ('Beinn Iutharn Mhòr', 1045, 3428, 'Cairngorms', '', '', 'Beinn Iutharn Mhòr is a 1045m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_iutharn_mhor.jpg'),
  ('Beinn Liath Mhòr', 926, 3038, 'Torridon', '', '', 'Beinn Liath Mhòr is a 926m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_liath_mhor.jpg'),
  ('Beinn Liath Mhòr Fannaich', 954, 3130, 'Ullapool', '', '', 'Beinn Liath Mhòr Fannaich is a 954m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_liath_mhor_fannaich.jpg'),
  ('Beinn Mhanach', 953, 3127, 'Argyll', '', '', 'Beinn Mhanach is a 953m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_mhanach.jpg'),
  ('Beinn Mheadhoin', 1182, 3878, 'Cairngorms', '', '', 'Beinn Mheadhoin is a 1182m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_mheadhoin.jpg'),
  ('Beinn na Lap', 937, 3074, 'Fort William', '', '', 'Beinn na Lap is a 937m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_na_lap.jpg'),
  ('Beinn nan Aighenan', 960, 3150, 'Fort William', '', '', 'Beinn nan Aighenan is a 960m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_nan_aighenan.jpg'),
  ('Beinn Narnain', 926, 3038, 'Loch Lomond', '', '', 'Beinn Narnain is a 926m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_narnain.jpg'),
  ('Beinn Sgritheall', 974, 3196, 'Kintail', '', '', 'Beinn Sgritheall is a 974m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_sgritheall.jpg'),
  ('Beinn Sgulaird', 937, 3074, 'Argyll', '', '', 'Beinn Sgulaird is a 937m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_sgulaird.jpg'),
  ('Beinn Tarsuinn', 937, 3074, 'Ullapool', '', '', 'Beinn Tarsuinn is a 937m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_tarsuinn.jpg'),
  ('Beinn Teallach', 915, 3002, 'Fort William', '', '', 'Beinn Teallach is a 915m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_teallach.jpg'),
  ('Beinn Tulaichean', 946, 3104, 'Loch Lomond', '', '', 'Beinn Tulaichean is a 946m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'beinn_tulaichean.jpg'),
  ('Beinn Udlamain', 1010, 3314, 'Cairngorms', '', '', 'Beinn Udlamain is a 1010m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'beinn_udlamain.jpg'),
  ('Ben Alder', 1148, 3766, 'Cairngorms', '', '', 'Ben Alder is a 1148m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_alder.jpg'),
  ('Ben Avon', 1171, 3842, 'Cairngorms', '', '', 'Ben Avon is a 1171m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_avon.jpg'),
  ('Ben Challum', 1025, 3363, 'Argyll', '', '', 'Ben Challum is a 1025m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_challum.jpg'),
  ('Ben Chonzie', 931, 3054, 'Perthshire', '', '', 'Ben Chonzie is a 931m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_chonzie.jpg'),
  ('Ben Cruachan', 1126, 3694, 'Argyll', '', '', 'Ben Cruachan is a 1126m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_cruachan.jpg'),
  ('Ben Hope', 927, 3041, 'Sutherland', '', '', 'Ben Hope is a 927m Munro located in Sutherland. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_hope.jpg'),
  ('Ben Klibreck', 961, 3153, 'Sutherland', '', '', 'Ben Klibreck is a 961m Munro located in Sutherland. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_klibreck.jpg'),
  ('Ben Lawers', 1214, 3983, 'Perthshire', '', '', 'Ben Lawers is a 1214m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'ben_lawers.jpg'),
  ('Ben Lomond', 974, 3196, 'Loch Lomond', '', '', 'Ben Lomond is a 974m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_lomond.jpg'),
  ('Ben Lui', 1130, 3707, 'Argyll', '', '', 'Ben Lui is a 1130m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_lui.jpg'),
  ('Ben Macdui', 1309, 4295, 'Cairngorms', '', '', 'Ben Macdui is a 1309m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'ben_macdui.jpg'),
  ('Ben More', 1174, 3852, 'Loch Lomond', '', '', 'Ben More is a 1174m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_more.jpg'),
  ('Ben More (Mull)', 966, 3169, 'Isle of Mull', '', '', 'Ben More (Mull) is a 966m Munro located in Isle of Mull. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_more.jpg'),
  ('Ben More Assynt', 998, 3274, 'Ullapool', '', '', 'Ben More Assynt is a 998m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_more_assynt.jpg'),
  ('Ben Nevis', 1345, 4413, 'Fort William', '', '', 'Ben Nevis is a 1345m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'ben_nevis.jpg'),
  ('Ben Oss', 1029, 3376, 'Argyll', '', '', 'Ben Oss is a 1029m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_oss.jpg'),
  ('Ben Starav', 1078, 3537, 'Fort William', '', '', 'Ben Starav is a 1078m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_starav.jpg'),
  ('Ben Vane', 915, 3002, 'Loch Lomond', '', '', 'Ben Vane is a 915m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_vane.jpg'),
  ('Ben Vorlich (Loch Earn)', 985, 3232, 'Perthshire', '', '', 'Ben Vorlich (Loch Earn) is a 985m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_vorlich.jpg'),
  ('Ben Vorlich (Loch Lomond)', 943, 3094, 'Loch Lomond', '', '', 'Ben Vorlich (Loch Lomond) is a 943m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ben_vorlich.jpg'),
  ('Ben Wyvis', 1046, 3432, 'Loch Ness', '', '', 'Ben Wyvis is a 1046m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ben_wyvis.jpg'),
  ('Bidean nam Bian', 1150, 3773, 'Fort William', '', '', 'Bidean nam Bian is a 1150m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'bidean_nam_bian.jpg'),
  ('Bidein a'' Choire Sheasgaich', 945, 3100, 'Torridon', '', '', 'Bidein a'' Choire Sheasgaich is a 945m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'bidein_a_choire_sheasgaich.jpg'),
  ('Bidein a'' Ghlas Thuill (An Teallach)', 1062, 3484, 'Ullapool', '', '', 'Bidein a'' Ghlas Thuill (An Teallach) is a 1062m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'bidein_a_ghlas_thuill.jpg'),
  ('Binnein Beag', 943, 3094, 'Fort William', '', '', 'Binnein Beag is a 943m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'binnein_beag.jpg'),
  ('Binnein Mòr', 1130, 3707, 'Fort William', '', '', 'Binnein Mòr is a 1130m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'binnein_mor.jpg'),
  ('Blà Bheinn', 928, 3045, 'Isle of Skye', '', '', 'Blà Bheinn is a 928m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'bla_bheinn.jpg'),
  ('Braeriach', 1296, 4252, 'Cairngorms', '', '', 'Braeriach is a 1296m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'braeriach.jpg'),
  ('Bràigh Coire Chruinn-bhalgain', 1070, 3510, 'Perthshire', '', '', 'Bràigh Coire Chruinn-bhalgain is a 1070m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'braigh_coire_chruinn_bhalgain.jpg'),
  ('Broad Cairn', 998, 3274, 'Cairngorms', '', '', 'Broad Cairn is a 998m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'broad_cairn.jpg'),
  ('Bruach na Frìthe', 958, 3143, 'Isle of Skye', '', '', 'Bruach na Frìthe is a 958m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'bruach_na_frithe.jpg'),
  ('Bynack More', 1090, 3576, 'Cairngorms', '', '', 'Bynack More is a 1090m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'bynack_more.jpg'),
  ('Cairn Bannoch', 1012, 3320, 'Cairngorms', '', '', 'Cairn Bannoch is a 1012m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'cairn_bannoch.jpg'),
  ('Cairn Gorm', 1245, 4085, 'Cairngorms', '', '', 'Cairn Gorm is a 1245m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'cairn_gorm.jpg'),
  ('Cairn of Claise', 1064, 3491, 'Cairngorms', '', '', 'Cairn of Claise is a 1064m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'cairn_of_claise.jpg'),
  ('Cairn Toul', 1291, 4236, 'Cairngorms', '', '', 'Cairn Toul is a 1291m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'cairn_toul.jpg'),
  ('Càrn a'' Chlamain', 963, 3159, 'Perthshire', '', '', 'Càrn a'' Chlamain is a 963m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_a_chlamain.jpg'),
  ('Càrn a'' Choire Bhòidheach', 1118, 3668, 'Cairngorms', '', '', 'Càrn a'' Choire Bhòidheach is a 1118m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_a_choire_bhoidheach.jpg'),
  ('Càrn a'' Ghèoidh', 975, 3199, 'Cairngorms', '', '', 'Càrn a'' Ghèoidh is a 975m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_a_gheoidh.jpg'),
  ('Càrn a'' Mhàim', 1037, 3402, 'Cairngorms', '', '', 'Càrn a'' Mhàim is a 1037m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_a_mhaim.jpg'),
  ('Càrn an Fhìdhleir (Càrn Ealar)', 994, 3261, 'Cairngorms', '', '', 'Càrn an Fhìdhleir (Càrn Ealar) is a 994m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_an_fhidhleir.jpg'),
  ('Càrn an Rìgh', 1029, 3376, 'Perthshire', '', '', 'Càrn an Rìgh is a 1029m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_an_righ.jpg'),
  ('Càrn an t-Sagairt Mòr', 1047, 3435, 'Cairngorms', '', '', 'Càrn an t-Sagairt Mòr is a 1047m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_an_t_sagairt_mor.jpg'),
  ('Càrn an Tuirc', 1019, 3343, 'Cairngorms', '', '', 'Càrn an Tuirc is a 1019m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_an_tuirc.jpg'),
  ('Càrn Aosda', 917, 3009, 'Cairngorms', '', '', 'Càrn Aosda is a 917m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_aosda.jpg'),
  ('Càrn Bhac', 946, 3104, 'Cairngorms', '', '', 'Càrn Bhac is a 946m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_bhac.jpg'),
  ('Càrn Dearg (Corrour)', 941, 3087, 'Fort William', '', '', 'Càrn Dearg (Corrour) is a 941m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_dearg.jpg'),
  ('Càrn Dearg (Loch Pattack)', 1034, 3392, 'Cairngorms', '', '', 'Càrn Dearg (Loch Pattack) is a 1034m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_dearg.jpg'),
  ('Càrn Dearg (Monadhliath)', 945, 3100, 'Cairngorms', '', '', 'Càrn Dearg (Monadhliath) is a 945m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_dearg.jpg'),
  ('Càrn Eige', 1183, 3881, 'Loch Ness', '', '', 'Càrn Eige is a 1183m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_eige.jpg'),
  ('Càrn Ghluasaid', 957, 3140, 'Kintail', '', '', 'Càrn Ghluasaid is a 957m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_ghluasaid.jpg'),
  ('Càrn Gorm', 1029, 3376, 'Perthshire', '', '', 'Càrn Gorm is a 1029m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_gorm.jpg'),
  ('Càrn Liath (Beinn a'' Ghlò)', 975, 3199, 'Perthshire', '', '', 'Càrn Liath (Beinn a'' Ghlò) is a 975m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_liath.jpg'),
  ('Càrn Liath (Creag Meagaidh)', 1006, 3301, 'Fort William', '', '', 'Càrn Liath (Creag Meagaidh) is a 1006m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_liath.jpg'),
  ('Càrn Mairg', 1042, 3419, 'Perthshire', '', '', 'Càrn Mairg is a 1042m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_mairg.jpg'),
  ('Càrn Mòr Dearg', 1220, 4003, 'Fort William', '', '', 'Càrn Mòr Dearg is a 1220m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'carn_mor_dearg.jpg'),
  ('Càrn na Caim', 941, 3087, 'Cairngorms', '', '', 'Càrn na Caim is a 941m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_na_caim.jpg'),
  ('Càrn nan Gabhar', 1121, 3678, 'Perthshire', '', '', 'Càrn nan Gabhar is a 1121m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'carn_nan_gabhar.jpg'),
  ('Càrn nan Gobhar (Loch Mullardoch)', 992, 3255, 'Loch Ness', '', '', 'Càrn nan Gobhar (Loch Mullardoch) is a 992m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_nan_gobhar.jpg'),
  ('Càrn nan Gobhar (Strathfarrar)', 992, 3255, 'Loch Ness', '', '', 'Càrn nan Gobhar (Strathfarrar) is a 992m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_nan_gobhar.jpg'),
  ('Càrn Sgulain', 920, 3018, 'Cairngorms', '', '', 'Càrn Sgulain is a 920m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'carn_sgulain.jpg'),
  ('Chno Dearg', 1046, 3432, 'Fort William', '', '', 'Chno Dearg is a 1046m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'chno_dearg.jpg'),
  ('Ciste Dhubh', 979, 3212, 'Kintail', '', '', 'Ciste Dhubh is a 979m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ciste_dhubh.jpg'),
  ('Cona'' Mheall', 978, 3209, 'Ullapool', '', '', 'Cona'' Mheall is a 978m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'cona_mheall.jpg'),
  ('Conival', 987, 3238, 'Ullapool', '', '', 'Conival is a 987m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'conival.jpg'),
  ('Creag a''Mhàim', 947, 3107, 'Kintail', '', '', 'Creag a''Mhàim is a 947m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'creag_amhaim.jpg'),
  ('Creag Leacach', 987, 3238, 'Cairngorms', '', '', 'Creag Leacach is a 987m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'creag_leacach.jpg'),
  ('Creag Meagaidh', 1130, 3707, 'Fort William', '', '', 'Creag Meagaidh is a 1130m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'creag_meagaidh.jpg'),
  ('Creag Mhòr (Glen Lochay)', 1047, 3435, 'Perthshire', '', '', 'Creag Mhòr (Glen Lochay) is a 1047m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'creag_mhor.jpg'),
  ('Creag Mhòr (Meall na Aighean)', 981, 3219, 'Perthshire', '', '', 'Creag Mhòr (Meall na Aighean) is a 981m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'creag_mhor.jpg'),
  ('Creag nan Dàmh', 918, 3012, 'Kintail', '', '', 'Creag nan Dàmh is a 918m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'creag_nan_damh.jpg'),
  ('Creag Pitridh', 924, 3031, 'Fort William', '', '', 'Creag Pitridh is a 924m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'creag_pitridh.jpg'),
  ('Creise', 1100, 3609, 'Fort William', '', '', 'Creise is a 1100m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'creise.jpg'),
  ('Cruach Àrdrain', 1046, 3432, 'Loch Lomond', '', '', 'Cruach Àrdrain is a 1046m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'cruach_ardrain.jpg'),
  ('Derry Cairngorm', 1155, 3789, 'Cairngorms', '', '', 'Derry Cairngorm is a 1155m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'derry_cairngorm.jpg'),
  ('Driesh', 947, 3107, 'Angus', '', '', 'Driesh is a 947m Munro located in Angus. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'driesh.jpg'),
  ('Druim Shionnach', 987, 3238, 'Kintail', '', '', 'Druim Shionnach is a 987m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'druim_shionnach.jpg'),
  ('Eididh nan Clach Geala', 927, 3041, 'Ullapool', '', '', 'Eididh nan Clach Geala is a 927m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'eididh_nan_clach_geala.jpg'),
  ('Fionn Bheinn', 933, 3061, 'Torridon', '', '', 'Fionn Bheinn is a 933m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'fionn_bheinn.jpg'),
  ('Gairich', 919, 3015, 'Fort William', '', '', 'Gairich is a 919m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'gairich.jpg'),
  ('Garbh Chioch Mhòr', 1013, 3323, 'Fort William', '', '', 'Garbh Chioch Mhòr is a 1013m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'garbh_chioch_mhor.jpg'),
  ('Geal chàrn (Laggan)', 1049, 3442, 'Fort William', '', '', 'Geal chàrn (Laggan) is a 1049m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'geal_charn.jpg'),
  ('Geal Chàrn (Monadhliath)', 926, 3038, 'Cairngorms', '', '', 'Geal Chàrn (Monadhliath) is a 926m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'geal_charn.jpg'),
  ('Geal-chàrn (Alder)', 1132, 3714, 'Cairngorms', '', '', 'Geal-chàrn (Alder) is a 1132m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'geal_charn.jpg'),
  ('Geal-chàrn (Drumochter)', 917, 3009, 'Cairngorms', '', '', 'Geal-chàrn (Drumochter) is a 917m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'geal_charn.jpg'),
  ('Glas Bheinn Mhòr', 997, 3271, 'Fort William', '', '', 'Glas Bheinn Mhòr is a 997m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'glas_bheinn_mhor.jpg'),
  ('Glas Maol', 1068, 3504, 'Cairngorms', '', '', 'Glas Maol is a 1068m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'glas_maol.jpg'),
  ('Glas Tulaichean', 1051, 3448, 'Perthshire', '', '', 'Glas Tulaichean is a 1051m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'glas_tulaichean.jpg'),
  ('Gleouraich', 1035, 3396, 'Fort William', '', '', 'Gleouraich is a 1035m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'gleouraich.jpg'),
  ('Gulvain', 987, 3238, 'Fort William', '', '', 'Gulvain is a 987m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'gulvain.jpg'),
  ('Inaccessible Pinnacle', 986, 3235, 'Isle of Skye', '', '', 'Inaccessible Pinnacle is a 986m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'inaccessible_pinnacle.jpg'),
  ('Ladhar Bheinn', 1020, 3346, 'Fort William', '', '', 'Ladhar Bheinn is a 1020m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ladhar_bheinn.jpg'),
  ('Lochnagar', 1156, 3793, 'Cairngorms', '', '', 'Lochnagar is a 1156m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'lochnagar.jpg'),
  ('Luinne Bheinn', 939, 3081, 'Fort William', '', '', 'Luinne Bheinn is a 939m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'luinne_bheinn.jpg'),
  ('Lurg Mhòr', 986, 3235, 'Torridon', '', '', 'Lurg Mhòr is a 986m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'lurg_mhor.jpg'),
  ('Màm Sodhail', 1181, 3875, 'Loch Ness', '', '', 'Màm Sodhail is a 1181m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'mam_sodhail.jpg'),
  ('Maoile Lunndaidh', 1007, 3304, 'Torridon', '', '', 'Maoile Lunndaidh is a 1007m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'maoile_lunndaidh.jpg'),
  ('Maol Chean-dearg', 933, 3061, 'Torridon', '', '', 'Maol Chean-dearg is a 933m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'maol_chean_dearg.jpg'),
  ('Maol chinn-dearg', 981, 3219, 'Kintail', '', '', 'Maol chinn-dearg is a 981m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'maol_chinn_dearg.jpg'),
  ('Mayar', 928, 3045, 'Angus', '', '', 'Mayar is a 928m Munro located in Angus. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'mayar.jpg'),
  ('Meall a'' Bhùiridh', 1108, 3635, 'Fort William', '', '', 'Meall a'' Bhùiridh is a 1108m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'meall_a_bhuiridh.jpg'),
  ('Meall a'' Choire Lèith', 926, 3038, 'Perthshire', '', '', 'Meall a'' Choire Lèith is a 926m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_a_choire_leith.jpg'),
  ('Meall a'' Chrasgaidh', 934, 3064, 'Ullapool', '', '', 'Meall a'' Chrasgaidh is a 934m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_a_chrasgaidh.jpg'),
  ('Meall Buidhe (Glen Lyon)', 932, 3058, 'Perthshire', '', '', 'Meall Buidhe (Glen Lyon) is a 932m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_buidhe.jpg'),
  ('Meall Buidhe (Knoydart)', 946, 3104, 'Fort William', '', '', 'Meall Buidhe (Knoydart) is a 946m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_buidhe.jpg'),
  ('Meall Chuaich', 951, 3120, 'Cairngorms', '', '', 'Meall Chuaich is a 951m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_chuaich.jpg'),
  ('Meall Corranaich', 1069, 3507, 'Perthshire', '', '', 'Meall Corranaich is a 1069m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'meall_corranaich.jpg'),
  ('Meall Dearg (Aonach Eagach)', 953, 3127, 'Fort William', '', '', 'Meall Dearg (Aonach Eagach) is a 953m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_dearg.jpg'),
  ('Meall Garbh (Ben Lawers)', 1118, 3668, 'Perthshire', '', '', 'Meall Garbh (Ben Lawers) is a 1118m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'meall_garbh.jpg'),
  ('Meall Garbh (Càrn Mairg)', 968, 3176, 'Perthshire', '', '', 'Meall Garbh (Càrn Mairg) is a 968m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_garbh.jpg'),
  ('Meall Ghaordaidh', 1039, 3409, 'Perthshire', '', '', 'Meall Ghaordaidh is a 1039m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'meall_ghaordaidh.jpg'),
  ('Meall Glas', 959, 3146, 'Loch Lomond', '', '', 'Meall Glas is a 959m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_glas.jpg'),
  ('Meall Gorm', 949, 3114, 'Ullapool', '', '', 'Meall Gorm is a 949m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_gorm.jpg'),
  ('Meall Greigh', 1001, 3284, 'Perthshire', '', '', 'Meall Greigh is a 1001m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'meall_greigh.jpg'),
  ('Meall na Teanga', 918, 3012, 'Fort William', '', '', 'Meall na Teanga is a 918m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_na_teanga.jpg'),
  ('Meall nan Ceapraichean', 977, 3205, 'Ullapool', '', '', 'Meall nan Ceapraichean is a 977m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_nan_ceapraichean.jpg'),
  ('Meall nan Eun', 928, 3045, 'Fort William', '', '', 'Meall nan Eun is a 928m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'meall_nan_eun.jpg'),
  ('Meall nan Tarmachan', 1044, 3425, 'Perthshire', '', '', 'Meall nan Tarmachan is a 1044m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'meall_nan_tarmachan.jpg'),
  ('Monadh Mòr', 1113, 3652, 'Cairngorms', '', '', 'Monadh Mòr is a 1113m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'monadh_mor.jpg'),
  ('Moruisg', 928, 3045, 'Torridon', '', '', 'Moruisg is a 928m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'moruisg.jpg'),
  ('Mount Keen', 939, 3081, 'Angus', '', '', 'Mount Keen is a 939m Munro located in Angus. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'mount_keen.jpg'),
  ('Mullach an Rathain (Liathach)', 1023, 3356, 'Torridon', '', '', 'Mullach an Rathain (Liathach) is a 1023m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'mullach_an_rathain.jpg'),
  ('Mullach Clach a'' Bhlàir', 1019, 3343, 'Cairngorms', '', '', 'Mullach Clach a'' Bhlàir is a 1019m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'mullach_clach_a_bhlair.jpg'),
  ('Mullach Coire Mhic Fhearchair', 1019, 3343, 'Ullapool', '', '', 'Mullach Coire Mhic Fhearchair is a 1019m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'mullach_coire_mhic_fhearchair.jpg'),
  ('Mullach Fraoch-choire', 1102, 3615, 'Kintail', '', '', 'Mullach Fraoch-choire is a 1102m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'mullach_fraoch_choire.jpg'),
  ('Mullach na Dheiragain', 982, 3222, 'Loch Ness', '', '', 'Mullach na Dheiragain is a 982m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'mullach_na_dheiragain.jpg'),
  ('Mullach nan Coirean', 939, 3081, 'Fort William', '', '', 'Mullach nan Coirean is a 939m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'mullach_nan_coirean.jpg'),
  ('Na Gruagaichean', 1056, 3465, 'Fort William', '', '', 'Na Gruagaichean is a 1056m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'na_gruagaichean.jpg'),
  ('Ruadh Stac Mòr', 918, 3012, 'Ullapool', '', '', 'Ruadh Stac Mòr is a 918m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'ruadh_stac_mor.jpg'),
  ('Ruadh-stac Mòr (Beinn Eighe)', 1010, 3314, 'Torridon', '', '', 'Ruadh-stac Mòr (Beinn Eighe) is a 1010m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'ruadh_stac_mor.jpg'),
  ('Sàil Chaorainn', 1002, 3287, 'Kintail', '', '', 'Sàil Chaorainn is a 1002m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sail_chaorainn.jpg'),
  ('Sàileag', 956, 3136, 'Kintail', '', '', 'Sàileag is a 956m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'saileag.jpg'),
  ('Schiehallion', 1083, 3553, 'Perthshire', '', '', 'Schiehallion is a 1083m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'schiehallion.jpg'),
  ('Seana Bhràigh', 926, 3038, 'Ullapool', '', '', 'Seana Bhràigh is a 926m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'seana_bhraigh.jpg'),
  ('Sgàirneach Mhòr', 991, 3251, 'Cairngorms', '', '', 'Sgàirneach Mhòr is a 991m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgairneach_mhor.jpg'),
  ('Sgiath Chùil', 921, 3022, 'Loch Lomond', '', '', 'Sgiath Chùil is a 921m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgiath_chuil.jpg'),
  ('Sgòr an Lochain Uaine', 1258, 4127, 'Cairngorms', '', '', 'Sgòr an Lochain Uaine is a 1258m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 4, 8, 'sgor_an_lochain_uaine.jpg'),
  ('Sgòr Gaibhre', 955, 3133, 'Fort William', '', '', 'Sgòr Gaibhre is a 955m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgor_gaibhre.jpg'),
  ('Sgòr Gaoith', 1118, 3668, 'Cairngorms', '', '', 'Sgòr Gaoith is a 1118m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgor_gaoith.jpg'),
  ('Sgòr na h-Ulaidh', 994, 3261, 'Fort William', '', '', 'Sgòr na h-Ulaidh is a 994m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgor_na_h_ulaidh.jpg'),
  ('Sgòrr Dhearg (Beinn a'' Bheithir)', 1024, 3360, 'Fort William', '', '', 'Sgòrr Dhearg (Beinn a'' Bheithir) is a 1024m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgorr_dhearg.jpg'),
  ('Sgòrr Dhònuill (Beinn a'' Bheithir)', 1001, 3284, 'Fort William', '', '', 'Sgòrr Dhònuill (Beinn a'' Bheithir) is a 1001m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgorr_dhonuill.jpg'),
  ('Sgòrr nam Fiannaidh (Aonach Eagach)', 967, 3173, 'Fort William', '', '', 'Sgòrr nam Fiannaidh (Aonach Eagach) is a 967m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgorr_nam_fiannaidh.jpg'),
  ('Sgòrr Ruadh', 962, 3156, 'Torridon', '', '', 'Sgòrr Ruadh is a 962m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgorr_ruadh.jpg'),
  ('Sgùrr a'' Bhealaich Dheirg', 1036, 3399, 'Kintail', '', '', 'Sgùrr a'' Bhealaich Dheirg is a 1036m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_a_bhealaich_dheirg.jpg'),
  ('Sgùrr a'' Chaorachain', 1053, 3455, 'Torridon', '', '', 'Sgùrr a'' Chaorachain is a 1053m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_a_chaorachain.jpg'),
  ('Sgùrr a'' Choire Ghlais', 1083, 3553, 'Loch Ness', '', '', 'Sgùrr a'' Choire Ghlais is a 1083m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_a_choire_ghlais.jpg'),
  ('Sgùrr a'' Ghreadaidh', 973, 3192, 'Isle of Skye', '', '', 'Sgùrr a'' Ghreadaidh is a 973m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_a_ghreadaidh.jpg'),
  ('Sgùrr a'' Mhadaidh', 918, 3012, 'Isle of Skye', '', '', 'Sgùrr a'' Mhadaidh is a 918m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_a_mhadaidh.jpg'),
  ('Sgùrr a'' Mhàim', 1099, 3606, 'Fort William', '', '', 'Sgùrr a'' Mhàim is a 1099m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_a_mhaim.jpg'),
  ('Sgùrr a'' Mhaoraich', 1027, 3369, 'Fort William', '', '', 'Sgùrr a'' Mhaoraich is a 1027m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_a_mhaoraich.jpg'),
  ('Sgùrr Alasdair', 992, 3255, 'Isle of Skye', '', '', 'Sgùrr Alasdair is a 992m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_alasdair.jpg'),
  ('Sgùrr an Doire Leathain', 1010, 3314, 'Kintail', '', '', 'Sgùrr an Doire Leathain is a 1010m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_an_doire_leathain.jpg'),
  ('Sgùrr an Lochain', 1004, 3294, 'Kintail', '', '', 'Sgùrr an Lochain is a 1004m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_an_lochain.jpg'),
  ('Sgùrr Bàn', 989, 3245, 'Ullapool', '', '', 'Sgùrr Bàn is a 989m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_ban.jpg'),
  ('Sgùrr Breac', 999, 3278, 'Ullapool', '', '', 'Sgùrr Breac is a 999m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_breac.jpg'),
  ('Sgùrr Chòinnich', 999, 3278, 'Torridon', '', '', 'Sgùrr Chòinnich is a 999m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_choinnich.jpg'),
  ('Sgùrr Chòinnich Mòr', 1094, 3589, 'Fort William', '', '', 'Sgùrr Chòinnich Mòr is a 1094m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_choinnich_mor.jpg'),
  ('Sgùrr Dubh Mòr', 944, 3097, 'Isle of Skye', '', '', 'Sgùrr Dubh Mòr is a 944m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_dubh_mor.jpg'),
  ('Sgùrr Èilde Mòr', 1010, 3314, 'Fort William', '', '', 'Sgùrr Èilde Mòr is a 1010m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_eilde_mor.jpg'),
  ('Sgùrr Fhuar-thuill', 1049, 3442, 'Loch Ness', '', '', 'Sgùrr Fhuar-thuill is a 1049m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_fhuar_thuill.jpg'),
  ('Sgùrr Fhuaran', 1067, 3501, 'Kintail', '', '', 'Sgùrr Fhuaran is a 1067m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_fhuaran.jpg'),
  ('Sgùrr Fiona (An Teallach)', 1060, 3478, 'Ullapool', '', '', 'Sgùrr Fiona (An Teallach) is a 1060m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_fiona.jpg'),
  ('Sgùrr Mhic Chòinnich', 948, 3110, 'Isle of Skye', '', '', 'Sgùrr Mhic Chòinnich is a 948m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_mhic_choinnich.jpg'),
  ('Sgùrr Mòr', 1110, 3642, 'Ullapool', '', '', 'Sgùrr Mòr is a 1110m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_mor.jpg'),
  ('Sgùrr Mòr (Beinn Alligin)', 986, 3235, 'Torridon', '', '', 'Sgùrr Mòr (Beinn Alligin) is a 986m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_mor.jpg'),
  ('Sgùrr Mòr (Loch Cuaich)', 1003, 3291, 'Fort William', '', '', 'Sgùrr Mòr (Loch Cuaich) is a 1003m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_mor.jpg'),
  ('Sgùrr na Banachdich', 965, 3166, 'Isle of Skye', '', '', 'Sgùrr na Banachdich is a 965m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_na_banachdich.jpg'),
  ('Sgùrr na Càrnach', 1002, 3287, 'Kintail', '', '', 'Sgùrr na Càrnach is a 1002m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_na_carnach.jpg'),
  ('Sgùrr na Cìche', 1040, 3412, 'Fort William', '', '', 'Sgùrr na Cìche is a 1040m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_na_ciche.jpg'),
  ('Sgùrr na Ciste Duibhe', 1027, 3369, 'Kintail', '', '', 'Sgùrr na Ciste Duibhe is a 1027m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_na_ciste_duibhe.jpg'),
  ('Sgùrr na Lapaich', 1150, 3773, 'Loch Ness', '', '', 'Sgùrr na Lapaich is a 1150m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_na_lapaich.jpg'),
  ('Sgùrr na Ruaidhe', 993, 3258, 'Loch Ness', '', '', 'Sgùrr na Ruaidhe is a 993m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_na_ruaidhe.jpg'),
  ('Sgùrr na Sgìne', 945, 3100, 'Kintail', '', '', 'Sgùrr na Sgìne is a 945m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_na_sgine.jpg'),
  ('Sgùrr nan Ceathreamhnan', 1151, 3776, 'Loch Ness', '', '', 'Sgùrr nan Ceathreamhnan is a 1151m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_nan_ceathreamhnan.jpg'),
  ('Sgùrr nan Clach Geala', 1093, 3586, 'Ullapool', '', '', 'Sgùrr nan Clach Geala is a 1093m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_nan_clach_geala.jpg'),
  ('Sgùrr nan Coireachan (Glen Dessary)', 953, 3127, 'Fort William', '', '', 'Sgùrr nan Coireachan (Glen Dessary) is a 953m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_nan_coireachan.jpg'),
  ('Sgùrr nan Coireachan (Glenfinnan)', 956, 3136, 'Fort William', '', '', 'Sgùrr nan Coireachan (Glenfinnan) is a 956m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_nan_coireachan.jpg'),
  ('Sgùrr nan Conbhairean', 1109, 3638, 'Kintail', '', '', 'Sgùrr nan Conbhairean is a 1109m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'sgurr_nan_conbhairean.jpg'),
  ('Sgùrr nan Each', 923, 3028, 'Ullapool', '', '', 'Sgùrr nan Each is a 923m Munro located in Ullapool. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_nan_each.jpg'),
  ('Sgùrr nan Eag', 924, 3031, 'Isle of Skye', '', '', 'Sgùrr nan Eag is a 924m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_nan_eag.jpg'),
  ('Sgùrr nan Gillean', 964, 3163, 'Isle of Skye', '', '', 'Sgùrr nan Gillean is a 964m Munro located in Isle of Skye. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_nan_gillean.jpg'),
  ('Sgùrr Thuilm', 963, 3159, 'Fort William', '', '', 'Sgùrr Thuilm is a 963m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sgurr_thuilm.jpg'),
  ('Slioch', 981, 3219, 'Torridon', '', '', 'Slioch is a 981m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'slioch.jpg'),
  ('Spidean a'' Choire Lèith (Liathach)', 1055, 3461, 'Torridon', '', '', 'Spidean a'' Choire Lèith (Liathach) is a 1055m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'spidean_a_choire_leith.jpg'),
  ('Spidean Coire nan Clach (Beinn Eighe)', 993, 3258, 'Torridon', '', '', 'Spidean Coire nan Clach (Beinn Eighe) is a 993m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'spidean_coire_nan_clach.jpg'),
  ('Spidean Mialach', 996, 3268, 'Fort William', '', '', 'Spidean Mialach is a 996m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'spidean_mialach.jpg'),
  ('Sròn a'' Choire Ghairbh', 937, 3074, 'Fort William', '', '', 'Sròn a'' Choire Ghairbh is a 937m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'sron_a_choire_ghairbh.jpg'),
  ('Stob a'' Choire Mheadhoin', 1106, 3629, 'Fort William', '', '', 'Stob a'' Choire Mheadhoin is a 1106m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_a_choire_mheadhoin.jpg'),
  ('Stob a'' Choire Odhair', 945, 3100, 'Argyll', '', '', 'Stob a'' Choire Odhair is a 945m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_a_choire_odhair.jpg'),
  ('Stob Bàn (Grey Corries)', 977, 3205, 'Fort William', '', '', 'Stob Bàn (Grey Corries) is a 977m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_ban.jpg'),
  ('Stob Bàn (Mamores)', 999, 3278, 'Fort William', '', '', 'Stob Bàn (Mamores) is a 999m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_ban.jpg'),
  ('Stob Binnein', 1165, 3822, 'Loch Lomond', '', '', 'Stob Binnein is a 1165m Munro located in Loch Lomond. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_binnein.jpg'),
  ('Stob Choire Claurigh', 1177, 3862, 'Fort William', '', '', 'Stob Choire Claurigh is a 1177m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_choire_claurigh.jpg'),
  ('Stob Coir an Albannaich', 1044, 3425, 'Fort William', '', '', 'Stob Coir an Albannaich is a 1044m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_coir_an_albannaich.jpg'),
  ('Stob Coire a'' Chàirn', 981, 3219, 'Fort William', '', '', 'Stob Coire a'' Chàirn is a 981m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_coire_a_chairn.jpg'),
  ('Stob Coire an Laoigh', 1116, 3661, 'Fort William', '', '', 'Stob Coire an Laoigh is a 1116m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_coire_an_laoigh.jpg'),
  ('Stob Coire Easain', 1115, 3658, 'Fort William', '', '', 'Stob Coire Easain is a 1115m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_coire_easain.jpg'),
  ('Stob Coire Raineach (Buachaille Etive Beag)', 925, 3035, 'Fort William', '', '', 'Stob Coire Raineach (Buachaille Etive Beag) is a 925m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_coire_raineach.jpg'),
  ('Stob Coire Sgreamhach', 1072, 3517, 'Fort William', '', '', 'Stob Coire Sgreamhach is a 1072m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_coire_sgreamhach.jpg'),
  ('Stob Coire Sgriodain', 979, 3212, 'Fort William', '', '', 'Stob Coire Sgriodain is a 979m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_coire_sgriodain.jpg'),
  ('Stob Daimh', 998, 3274, 'Argyll', '', '', 'Stob Daimh is a 998m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_daimh.jpg'),
  ('Stob Dearg (Buachaille Etive Mòr)', 1021, 3350, 'Fort William', '', '', 'Stob Dearg (Buachaille Etive Mòr) is a 1021m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_dearg.jpg'),
  ('Stob Dubh (Buachaille Etive Beag)', 956, 3136, 'Fort William', '', '', 'Stob Dubh (Buachaille Etive Beag) is a 956m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_dubh.jpg'),
  ('Stob Ghabhar', 1090, 3576, 'Argyll', '', '', 'Stob Ghabhar is a 1090m Munro located in Argyll. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_ghabhar.jpg'),
  ('Stob na Bròige (Buachaille Etive Mòr)', 956, 3136, 'Fort William', '', '', 'Stob na Bròige (Buachaille Etive Mòr) is a 956m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stob_na_broige.jpg'),
  ('Stob Poite Coire Àrdair', 1054, 3458, 'Fort William', '', '', 'Stob Poite Coire Àrdair is a 1054m Munro located in Fort William. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'stob_poite_coire_ardair.jpg'),
  ('Stùc a'' Chròin', 975, 3199, 'Perthshire', '', '', 'Stùc a'' Chròin is a 975m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stuc_a_chroin.jpg'),
  ('Stùcd an Lochain', 960, 3150, 'Perthshire', '', '', 'Stùcd an Lochain is a 960m Munro located in Perthshire. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'stucd_an_lochain.jpg'),
  ('The Cairnwell', 933, 3061, 'Cairngorms', '', '', 'The Cairnwell is a 933m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'the_cairnwell.jpg'),
  ('The Devil''s Point', 1004, 3294, 'Cairngorms', '', '', 'The Devil''s Point is a 1004m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'the_devils_point.jpg'),
  ('The Saddle', 1010, 3314, 'Kintail', '', '', 'The Saddle is a 1010m Munro located in Kintail. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'the_saddle.jpg'),
  ('Toll Creagach', 1054, 3458, 'Loch Ness', '', '', 'Toll Creagach is a 1054m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'toll_creagach.jpg'),
  ('Tolmount', 958, 3143, 'Cairngorms', '', '', 'Tolmount is a 958m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'tolmount.jpg'),
  ('Tom a'' Chòinich', 1112, 3648, 'Loch Ness', '', '', 'Tom a'' Chòinich is a 1112m Munro located in Loch Ness. This peak offers excellent views and is a popular destination for hillwalkers.', 3, 6.5, 'tom_a_choinich.jpg'),
  ('Tom Buidhe', 957, 3140, 'Cairngorms', '', '', 'Tom Buidhe is a 957m Munro located in Cairngorms. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'tom_buidhe.jpg'),
  ('Tom na Gruagaich (Beinn Alligin)', 922, 3025, 'Torridon', '', '', 'Tom na Gruagaich (Beinn Alligin) is a 922m Munro located in Torridon. This peak offers excellent views and is a popular destination for hillwalkers.', 2, 5.5, 'tom_na_gruagaich.jpg');

-- Verify the data
SELECT 
  COUNT(*) as total_munros,
  MIN(height_m) as min_height,
  MAX(height_m) as max_height,
  COUNT(DISTINCT region) as regions
FROM munros;

-- Show sample data
SELECT name, height_m, region FROM munros ORDER BY height_m DESC LIMIT 10;
